openapi: 3.0.1
info:
  title: Product Catalog
  description: 'This is a sample product catalog'
  version: 1.0.0
servers:
- url: https://localhost:8080/v1
tags:
- name: products
  description: Everything about our Products
paths:
  /products:
    get:
      tags:
      - products
      summary: Get all products
      operationId: getProducts
      responses:
        200:
          description: successful operation
          content:
            application/xml:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
        400:
          description: Invalid status value
          content: {}
components:
  schemas:
    Product:
      type: object
      properties:
        id:
          type: integer
          format: int64
        productName:
          type: string
        productDescription:
          type: string
        productSubcategory:
          type: string
        prodSubcategoryId:
          type: integer
        productSubcategoryDescription:
          type: string
        productCategory:
          type: string
        productCategoryId:
          type: string
        productCategoryDescription:
          type: string
        productWeightClass:
          type: integer
        productUnitOfMeasure:
          type: string
        productPackSize:
          type: string
        supplierId:
          type: integer
        productStatus:
          type: string
        productListPrice:
          type: number
        productMinPrice:
          type: number
        productTotal:
          type: string
        productTotalId:
          type: integer
        productSourceId:
          type: integer
        productEffectiveFrom:
          type: string
        productEffectiveTo:
          type: string
        productValid:
          type: string